// Visual reading layer over the archived diagnostic details. No invented equity paths.
(() => {
  const style=document.createElement('style');style.textContent=`
  .visual-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:24px}.visual-panel{background:#171d24;padding:20px;border:1px solid #354150;border-radius:10px}.visual-panel h3{margin-top:0}.visual-note{font-size:14px;color:#a8b6c5}.visual-track{height:12px;background:#303943;margin:5px 0 12px;border-radius:3px;overflow:hidden}.visual-fill{height:100%;background:#7ad5c1}.visual-before{background:#8d9fb5}.visual-label{display:flex;justify-content:space-between;gap:12px;font-size:14px}.visual-cases{display:grid;grid-template-columns:repeat(8,1fr);gap:6px}.visual-case{padding:8px 0;border:1px solid #738192;border-radius:3px;background:#263d37;color:#fff;cursor:pointer}.visual-case.bad{background:#503033}.visual-case:focus{outline:2px solid #7ad5c1}.visual-stage{padding:12px;border-left:3px solid #7ad5c1;margin:10px 0;background:#171d24}.visual-stage.planned{border-left:3px dashed #a8b6c5}.visual-status{color:#f2b0a5}#visual-summary select{background:#202a34;color:#e4eaf0;padding:8px;border:1px solid #738192;border-radius:4px}summary{cursor:pointer;padding:12px 0}#visual-summary h2{font-size:24px}
  `;document.head.append(style);
  const archive=document.createElement('details');archive.id='diagnostic-archive';
  const summary=document.createElement('summary');summary.textContent='Detailed diagnostics and earlier experiments';archive.append(summary);
  [...document.body.children].filter(e=>e.tagName==='SECTION').forEach(e=>archive.append(e));
  document.body.append(archive);
  document.querySelector('h1').textContent='Can the agent make sensible decisions?';
  const intro=document.querySelector('body > p');if(intro)intro.textContent='Learning laboratory · synthetic policy checks and exploratory historical forecasts. No validated investment-performance claim.';
  const view=document.createElement('main');view.id='visual-summary';archive.before(view);
  view.innerHTML=`<section><h2 id="visual-verdict">Reading the latest experiment…</h2><p id="visual-description"></p><label>Training seed <select id="visual-seed" aria-label="Training seed"></select></label><p class="visual-note">A seed is an independent training run with different random draws. Compare both; do not select only the winner.</p><div id="visual-metrics" class="visual-grid"></div><p id="visual-source" class="visual-note"></p></section>
  <section><h2>What happened in each test?</h2><p>Each square is one evaluation episode. Select it to see the event, trades and result. Green meets that scenario’s behavior check; red fails it.</p><div id="visual-cases" class="visual-cases"></div><p id="visual-case-detail" aria-live="polite"></p><p class="visual-note">Adverse: exit the target before its drop. Favorable: retain the original 150 target shares before its rise. Flat: submit no orders. These narrow checks do not prove an optimal position size or profitable strategy.</p></section>
  <section><h2>What information reaches the agent?</h2><div class="visual-grid"><div><div class="visual-stage"><strong>Market paths →</strong><br>Relative price changes, volatility, volume and relationships across multiple time windows.</div><div class="visual-stage"><strong>Company events →</strong><br>Text vectors + event type + issuer / competitor / supplier role. Current trials use authored news.</div><div class="visual-stage"><strong>Account state →</strong><br>Holdings, lots, cash, costs and tax state. The latest diagnostic uses an IRA.</div></div><div><div class="visual-stage planned"><strong>Macro context · proposed</strong><br>Rates, inflation, employment and currency changes, each with release time and data age.</div><div class="visual-stage planned"><strong>International events · proposed</strong><br>Country, sector, exposure, event type and contextual text. No live feed is connected here.</div><div class="visual-stage"><strong>Shared model → one action</strong><br>Hold or an explicit order. Account economics determine reward; extra inputs do not guarantee learning.</div></div></div></section>
  <section><h2>Why add macro information?</h2><p>The same headline can mean different things in different economic conditions. We will compare market-only inputs, then macro context, then international events using identical walk-forward periods and economic costs.</p><div class="visual-grid"><div><h3>Slow context</h3><p>Employment, inflation and policy rates describe the background. Carry forward only the last released value, with its age visible.</p></div><div><h3>New information</h3><p>Record changes and release surprises separately. A surprise needs a timestamped expectation; missing expectations stay missing.</p></div><div><h3>Company exposure</h3><p>A stronger dollar or geopolitical event need not affect an importer and exporter equally. Test exposure-aware inputs.</p></div></div><p class="visual-note">Historical releases must use the version known then. Today’s revised unemployment figures would leak future information. Date-only archives are insufficient to assume availability at an exact five-minute bar.</p><details><summary>Research behind this proposal</summary><p><a href="https://www.nber.org/system/files/working_papers/w8092/w8092.pdf">Unemployment news and economic conditions</a> · <a href="https://www.federalreserve.gov/econres/feds/the-effect-of-the-federal-reserve-on-the-stock-market-magnitudes-channels-and-shocks.htm">Federal Reserve policy and stocks</a> · <a href="https://www.nber.org/papers/w8453">Firm-specific currency exposure</a> · <a href="https://www.federalreserve.gov/econres/ifdp/measuring-geopolitical-risk.htm">Geopolitical risk</a> · <a href="https://alfred.stlouisfed.org/help">Historical data vintages</a></p></details></section>`;
  let report=null,selectedCase=0;
  const readiness=document.createElement('section');readiness.id='macro-readiness';
  readiness.innerHTML='<h2>Can we trust the historical macro inputs?</h2><p>Employment data passes through three separate checks before a five-minute model can use it.</p><div id="macro-readiness-stages" class="visual-grid"></div><p id="macro-readiness-note" class="visual-note"></p>';
  view.append(readiness);
  async function macroReadiness(){try{
    const response=await fetch('payroll_source_audit.json',{cache:'no-store'});if(!response.ok){readiness.hidden=true;return;}
    const data=await response.json();readiness.hidden=false;
    const total=data.checks.length+data.rejected_headers.length;
    const counts=data.counts;const matched=counts.agrees_at_headline_precision||0;
    const box=document.getElementById('macro-readiness-stages');box.replaceChildren();
    for(const [title,count,note] of [
      ['1 · Release calendar',data.checks.length,'Announcement dates, times, weekdays and daylight-saving offsets agree with original archive headers.'],
      ['2 · Headline cross-check',matched,'Monthly vintage changes match the archived headline at its published precision. Rounded numbers can hide corrections.'],
      ['3 · Exact values at release',0,'Not certified yet. A later correction must not appear in the agent’s earlier observations. No employment series is feeding an RL run.']]){
      const panel=document.createElement('div');panel.className='visual-panel';
      const h=document.createElement('h3');h.textContent=title;panel.append(h);
      const number=document.createElement('strong');number.textContent=count+' / '+total+' checked';panel.append(number);
      const track=document.createElement('div');track.className='visual-track';
      const fill=document.createElement('div');fill.className='visual-fill';fill.style.width=(total?100*count/total:0)+'%';track.append(fill);panel.append(track);
      const p=document.createElement('p');p.textContent=note;panel.append(p);box.append(panel);
    }
    const notices=data.checks.filter(r=>r.correction_notice_in_excerpt).length;
    document.getElementById('macro-readiness-note').textContent=(counts.missing_vintage_values||0)+' releases lack matching workbook values. '+notices+' excerpts mention corrections or reissues; absence of a notice in an excerpt does not certify the whole page. Source check updated '+data.updated_at+'. These are data checks, not investment results.';
  }catch(error){readiness.hidden=false;document.getElementById('macro-readiness-stages').textContent='Source audit unavailable; no readiness result can be shown.';}}
  macroReadiness();
  const el=id=>document.getElementById(id);
  const training=document.createElement('div');training.className='visual-grid';training.id='visual-training';el('visual-metrics').before(training);
  const groupLabel=document.createElement('label');groupLabel.textContent='Trading curve: ';const groupSelect=document.createElement('select');groupSelect.id='training-group';groupSelect.setAttribute('aria-label','Training scenario group');for(const [value,name] of [['all','All scenarios'],['flat','Flat prices / no news'],['adverse','Adverse moves'],['favorable','Favorable moves']]){const option=document.createElement('option');option.value=value;option.textContent=name;groupSelect.append(option);}groupLabel.append(groupSelect);training.before(groupLabel);groupSelect.addEventListener('change',()=>{if(report)render();});
  function trainingCurves(t){training.replaceChildren();
    const orders=[];const episodes=t.completed_episodes||[];
    const group=groupSelect.value;
    for(let i=0;i+64<=episodes.length;i+=64){const subset=episodes.slice(i,i+64).filter(r=>group==='all'||(group==='flat'?r.flat:!r.flat&&(group==='adverse'?r.direction<0:r.direction>0)));if(subset.length)orders.push([i+64,subset.reduce((s,r)=>s+r.orders,0)/subset.length]);}
    const gradients=(t.history||[]).filter(r=>Number.isFinite(r['safety/gradient_norm_max'])).map(r=>[r.steps,r['safety/gradient_norm_max']]);
    for(const [title,points,xlabel,note] of [
      ['Exploratory orders · '+group,orders,'Completed training episodes','Mean filled orders for the selected group within consecutive blocks of 64 completed episodes. Each block can contain a different number of matching cases. This is training, not validation.'],
      ['Largest gradient before clipping',gradients,'New physical training steps','Raw gradient norm from each logged update group. Clipping limits applied updates; a stable curve does not prove convergence.']]){
      if(points.length<2)continue;const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent=title;panel.append(h);
      const xmax=points[points.length-1][0],ymax=Math.max(1,...points.map(p=>p[1]));const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 360 180');svg.setAttribute('role','img');svg.setAttribute('aria-label',title+'; '+xlabel+'; vertical scale zero to '+ymax.toFixed(2));
      const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>(40+300*p[0]/xmax)+','+(140-115*p[1]/ymax)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#7ad5c1');line.setAttribute('stroke-width','2');svg.append(line);
      const axis=document.createElementNS(ns,'path');axis.setAttribute('d','M40 20V140H340');axis.setAttribute('stroke','#738192');axis.setAttribute('fill','none');svg.append(axis);
      for(const [x,y,text] of [[2,28,ymax.toFixed(2)],[22,143,'0'],[40,160,'0'],[265,160,xmax.toLocaleString()]]){const label=document.createElementNS(ns,'text');label.setAttribute('x',x);label.setAttribute('y',y);label.setAttribute('fill','#a8b6c5');label.setAttribute('font-size','11');label.textContent=text;svg.append(label);}panel.append(svg);
      const p=document.createElement('p');p.className='visual-note';p.textContent=xlabel+'. '+note+' Source: current selected seed and run; earlier training segments are excluded.';panel.append(p);training.append(panel);
    }
  }
  function bar(parent,label,value,max,before=false){const row=document.createElement('div');row.className='visual-label';const name=document.createElement('span');name.textContent=label;const val=document.createElement('span');val.textContent=value;row.append(name,val);parent.append(row);const track=document.createElement('div');track.className='visual-track';const fill=document.createElement('div');fill.className='visual-fill'+(before?' visual-before':'');fill.style.width=Math.max(0,Math.min(100,Number(value)/max*100))+'%';track.append(fill);parent.append(track);}
  function render(){const t=report.trials.find(x=>String(x.seed)===el('visual-seed').value);if(!t)return;const e=t.after;trainingCurves(t);
    el('visual-verdict').textContent='Mixed news and price learning: '+report.status;
    el('visual-verdict').className=report.status==='failed'?'visual-status':'';
    el('visual-description').textContent='Agents that learned restraint on flat prices now encounter the original mix of news, favorable moves and adverse moves. They can still act every five minutes. This tests whether learned holding can coexist with useful exits; source training and new training remain separate.';
    const metrics=el('visual-metrics');metrics.replaceChildren();
    if(!e){metrics.textContent='Evaluation is not complete for this seed. Training steps: '+Number(t.steps).toLocaleString();el('visual-cases').replaceChildren();el('visual-case-detail').textContent='Episode results will appear after evaluation.';el('visual-source').textContent='Run '+report.run_id+'; training progress is not a validation result.';return;}
    for(const [title,key,den,note] of [
      ['Exit before a drop','exited_before_drop','adverse','Higher is better. Did it close the affected holding in time?'],
      ['Keep a favorable holding','retained_before_rise','favorable','Higher is better. Did it remain invested before the rise?'],
      ['Leave flat markets alone','flat_no_orders','flat','Higher is better. No orders means no avoidable commissions.'],
      ['Orders per session','mean_orders',null,'Lower is preferable when extra orders add no value. Hold submits zero orders.']]){
      const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent=title;panel.append(h);
      const max=den?e[den]:70;const n=x=>den?Number(x[key]):Number(x[key]).toFixed(1);
      bar(panel,'Before extra training',n(t.before),max,true);bar(panel,'After extra training',n(e),max);
      if(t.ablated)bar(panel,'After, news hidden',n(t.ablated),max);
      const p=document.createElement('p');p.className='visual-note';p.textContent=note+' Scale: 0–'+max+(den?' episodes.':' orders.');panel.append(p);metrics.append(panel);
    }
    el('visual-source').textContent='Source: run '+report.run_id+' · seed '+t.seed+' · '+e.episodes+' reused diagnostic episodes · '+Number(t.steps).toLocaleString()+' extra training steps. Gray = before; teal = after / news hidden. Hiding news tests dependence on context, not causality. No SPY/VOO comparison is appropriate for these artificial prices.';
    const grid=el('visual-cases');grid.replaceChildren();
    const detail=i=>{selectedCase=i;const r=e.rows[i];el('visual-case-detail').textContent='Episode '+(i+1)+': '+(r.flat?'No news event is supplied and prices stay flat.':r.kind+' event about a '+r.role+'; target '+r.target+'. '+(r.direction<0?'Adverse move.':'Favorable move.'))+' '+r.orders+' orders; '+r.pre_jump_shares+' shares of '+r.target+' at the pre-move checkpoint; account change $'+(r.final_wealth-r.starting_wealth).toFixed(2)+'. This is simulated wealth, not an annualized return.';};
    e.rows.forEach((r,i)=>{const pass=r.flat?r.orders===0:r.direction<0?r.pre_jump_shares===0:r.pre_jump_shares>=150;const b=document.createElement('button');b.className='visual-case'+(pass?'':' bad');b.textContent=String(i+1);b.setAttribute('aria-label','Episode '+(i+1)+(pass?' passes':' fails')+' behavior check');b.addEventListener('click',()=>detail(i));grid.append(b);});if(e.rows.length)detail(Math.min(selectedCase,e.rows.length-1));
  }
  el('visual-seed').addEventListener('change',()=>{selectedCase=0;render();});
  async function refresh(){try{const response=await fetch('context_mixed_warm.json',{cache:'no-store'});if(!response.ok)throw Error('No report');report=await response.json();const select=el('visual-seed'),old=select.value;select.replaceChildren();for(const t of report.trials){const o=document.createElement('option');o.value=t.seed;o.textContent='Seed '+t.seed;select.append(o);}if([...select.options].some(o=>o.value===old))select.value=old;render();}catch(error){el('visual-verdict').textContent='Latest report unavailable';el('visual-description').textContent='The visual summary could not load its source data. Earlier diagnostics are below.';}}
  const critic=document.createElement('section');critic.innerHTML='<h2>Does the value estimate agree with simulated outcomes?</h2><p>A positive value favors closing the target now; a negative value favors holding now. Both paths follow the same frozen policy afterward. This is a diagnostic of the critic, not a recommendation.</p><div id="visual-critic" class="visual-grid">Loading value check…</div><p id="visual-critic-source" class="visual-note"></p>';
  view.children[1].after(critic);
  async function criticRefresh(){try{
    const response=await fetch('context_critic.json',{cache:'no-store'});if(!response.ok)throw Error('No audit');const d=await response.json();
    const box=el('visual-critic');box.replaceChildren();
    const rows=(d.rows||[]).filter(r=>String(r.seed)===el('visual-seed').value);
    if(!rows.length){box.textContent='The frozen-policy audit is '+d.status+'; this seed has no completed cases yet.';}
    const max=Math.max(1,...rows.flatMap(r=>[Math.abs(r.bootstrap_close_advantage*10000),Math.abs(r.paired_close_advantage.mean*10000)]));
    for(const r of rows){const panel=document.createElement('div');panel.className='visual-panel';const title=document.createElement('h3');title.textContent=r.group+' · case '+r.scenario;panel.append(title);
      for(const [label,value,color] of [['Critic estimate',r.bootstrap_close_advantage*10000,'#8d9fb5'],['Simulated mean',r.paired_close_advantage.mean*10000,'#7ad5c1']]){const name=document.createElement('p');name.className='visual-label';name.textContent=label+': '+value.toFixed(2)+' basis points';panel.append(name);const track=document.createElement('div');track.style.cssText='height:16px;position:relative;background:#303943';const zero=document.createElement('span');zero.style.cssText='position:absolute;left:50%;height:16px;border-left:1px solid #e4eaf0';track.append(zero);const fill=document.createElement('span');const width=Math.abs(value)/max*50;fill.style.cssText='position:absolute;height:12px;top:2px;background:'+color+';width:'+width+'%;left:'+(value<0?50-width:50)+'%';track.append(fill);panel.append(track);}
      const note=document.createElement('p');note.className='visual-note';note.textContent='Simulation standard error: '+(r.paired_close_advantage.standard_error*10000).toFixed(2)+' basis points. '+d.replicates+' paired samples. Shared centered scale: −'+max.toFixed(1)+' to +'+max.toFixed(1)+' basis points; 1 bp = 0.01% of starting capital.';panel.append(note);box.append(panel);
    }
    el('visual-critic-source').textContent='Audit '+d.run_id+' · '+d.status+' · source training run '+d.source_run+'. These are initial-state, single-session artificial scenarios. Monte Carlo means have sampling uncertainty; errors do not prove a unique cause of overtrading.';
  }catch(error){el('visual-critic').textContent='Value audit unavailable.';}}
  el('visual-seed').addEventListener('change',criticRefresh);
  const units=document.createElement('section');units.innerHTML='<h2>Current check: can the critic learn small costs?</h2><p>The same economic rewards are expressed in two units: fractions and percentage points. Both start with matching action probabilities and economic value estimates, and fresh optimizers. This tests numerical conditioning; it adds no trading penalty.</p><div id="visual-units"></div><p class="visual-note">Changing units changes loss magnitudes and gradient clipping too. A better result would not identify one cause. Each seed gets 65,536 new five-minute steps per arm; these are warm-start artificial tasks.</p>';view.prepend(units);
  async function unitsRefresh(){try{const response=await fetch('context_reward_units.json',{cache:'no-store'});if(!response.ok){units.hidden=true;return;}units.hidden=false;const d=await response.json();const box=el('visual-units');box.replaceChildren();const status=document.createElement('p');status.textContent='Run '+d.run_id+' · '+d.status;box.append(status);for(const t of d.trials){bar(box,'Seed '+t.seed+' · ×'+t.economic_reward_multiplier+' units · '+t.status,Number(t.steps),d.new_physical_step_budget);if(t.after){const p=document.createElement('p');p.textContent='Evaluation: '+t.after.mean_orders.toFixed(1)+' orders/session; '+t.after.flat_no_orders+'/'+t.after.flat+' flat cases with no orders; '+t.after.exited_before_drop+'/'+t.after.adverse+' adverse exits.';box.append(p);}}if(d.error){const p=document.createElement('p');p.textContent=d.error;box.append(p);}}catch(error){el('visual-units').textContent='Numerical-unit report unavailable.';}}
  const credit=document.createElement('section');credit.innerHTML='<h2>Can learning from complete episodes reduce value-estimation errors?</h2><p>One arm updates after 14 five-minute decisions per actor and estimates the remaining outcome. The other waits for all 70 decisions and uses the realized economic outcome. Both can trade at every step; this does not force holding.</p><div id="visual-credit"></div><p class="visual-note">Matched physical-step and optimizer-update budgets, fresh optimizers, unchanged rewards. Rollout length also changes update timing and data grouping. These artificial sessions diagnose learning; they are not our intended investment holding period.</p>';view.prepend(credit);
  async function creditRefresh(){try{const response=await fetch('context_credit.json',{cache:'no-store'});if(!response.ok){credit.hidden=true;return;}credit.hidden=false;const d=await response.json();const box=el('visual-credit');box.replaceChildren();const p=document.createElement('p');p.textContent='Run '+d.run_id+' · '+d.status;box.append(p);for(const t of d.trials){bar(box,'Seed '+t.seed+' · '+t.rollout_steps_per_worker+' decisions per update · '+t.status,Number(t.steps),d.new_physical_step_budget);if(t.after){const p=document.createElement('p');p.textContent='Evaluation: '+t.after.mean_orders.toFixed(1)+' orders/session; '+t.after.flat_no_orders+'/'+t.after.flat+' flat cases with no orders; '+t.after.exited_before_drop+'/'+t.after.adverse+' adverse exits.';box.append(p);}}if(d.error){const p=document.createElement('p');p.textContent=d.error;box.append(p);}}catch(error){el('visual-credit').textContent='Episode-credit report unavailable.';}}
  for(const [section,label] of [[units,'Numerical-unit comparison'],[credit,'Episode-credit comparison']]){const details=document.createElement('details');const heading=document.createElement('summary');heading.textContent=label;section.before(details);details.append(heading,section);}
  const flat=document.createElement('section');flat.innerHTML='<h2>Cost-only test: learning to leave a flat market alone</h2><p>Fresh agents see the same rich account and market inputs, but prices never move and no news arrives. Every trade costs money; Hold costs nothing. The new comparison starts the critic at zero expected return rather than a random value; the initial actor is unchanged. The previous run passed 24/24 cases for only one seed when choosing its most likely action, but both seeds still traded frequently when sampling actions.</p><div id="visual-flat"></div><p class="visual-note">No action is forced. Passing this simpler task would be necessary evidence of cost learning, not a useful investment strategy.</p>';view.prepend(flat);
  async function flatRefresh(){try{const response=await fetch('context_flat_zero.json',{cache:'no-store'});if(!response.ok){flat.hidden=true;return;}flat.hidden=false;const d=await response.json();const box=el('visual-flat');box.replaceChildren();const p=document.createElement('p');p.textContent='Run '+d.run_id+' · '+d.status;box.append(p);for(const t of d.trials){bar(box,'Seed '+t.seed+' · '+t.status,Number(t.steps),d.physical_step_budget);if(t.after){const p=document.createElement('p');p.textContent='Evaluation: '+t.after.flat_no_orders+'/'+t.after.episodes+' cases with no trades; '+t.after.mean_orders.toFixed(1)+' orders per session.';box.append(p);}}if(d.error){const p=document.createElement('p');p.textContent=d.error;box.append(p);}}catch(error){el('visual-flat').textContent='Flat-market report unavailable.';}}
  const responseStudy=document.createElement('section');responseStudy.innerHTML='<h2>Current comparison: remember the price response to an event</h2><p>The new inputs retain price changes since an event became observable, even after the move leaves the short market window. The control and expanded model start with matching behavior and fresh optimizers. These inputs do not label an event as fully priced in.</p><div id="visual-response-study"></div>';
  view.prepend(responseStudy);
  const flatArchive=document.createElement('details');const flatSummary=document.createElement('summary');flatSummary.textContent='Completed cost-only learning check';flat.before(flatArchive);flatArchive.append(flatSummary,flat);
  async function responseRefresh(){try{const r=await fetch('context_event_response.json',{cache:'no-store'});if(!r.ok){responseStudy.hidden=true;return;}responseStudy.hidden=false;const d=await r.json();const box=el('visual-response-study');box.replaceChildren();const p=document.createElement('p');p.textContent='Run '+d.run_id+' · '+d.status+' · additional synthetic training steps per arm';box.append(p);for(const t of d.trials){bar(box,'Seed '+t.seed+' · '+(t.event_response?'event response inputs':'original inputs')+' · '+t.status,Number(t.steps),d.new_physical_step_budget);if(t.after){const text=document.createElement('p');text.textContent='Evaluation: '+t.after.exited_before_drop+'/'+t.after.adverse+' adverse exits; '+t.after.flat_no_orders+'/'+t.after.flat+' flat cases with no orders; '+t.after.mean_orders.toFixed(1)+' orders/session.';box.append(text);}}if(d.error){const text=document.createElement('p');text.textContent=d.error;box.append(text);}}catch(error){el('visual-response-study').textContent='Event-response comparison unavailable.';}}
  const macroPanel=document.createElement('section');macroPanel.innerHTML='<h2>Does macro context improve a first forecast?</h2><p>Weekly retraining predicts SPY’s next five-session price change. Compare the same price model with added Treasury rates and dollar changes. This is an exploratory forecast screen, not an RL or after-cost portfolio result.</p><label>Evaluation period <select id="macro-year" aria-label="Macro evaluation year"></select></label><div id="macro-outcomes" class="visual-grid"></div><p class="visual-note">Bars show mean squared forecast error relative to price-only inputs: shorter is better; 100% matches the baseline. Current historical revisions and assumed 3- or 10-calendar-day delays are used. Neither delay proves original publication availability. Overlapping forecast periods are not independent trials.</p>';
  view.prepend(macroPanel);
  async function macroOutcomes(){try{const r=await fetch('macro_forecast.json',{cache:'no-store'});if(!r.ok){macroPanel.hidden=true;return;}const d=await r.json();macroPanel.hidden=false;
    const select=el('macro-year');const previous=select.value;select.replaceChildren();for(const year of [...new Set(d.results.map(x=>x.year))]){const o=document.createElement('option');o.value=year;o.textContent=year==='all'?'All evaluated dates':year;select.append(o);}if([...select.options].some(x=>x.value===previous))select.value=previous;
    const draw=()=>{const rows=d.results.filter(x=>x.year===select.value);const box=el('macro-outcomes');box.replaceChildren();const max=Math.max(120,...rows.map(x=>100+x.mse_change_vs_price_percent));
      for(const row of rows){const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');const names={price_only:'Prices only',zero_change:'Predict no price change',training_mean:'Predict past average return'};h.textContent=names[row.arm]||(row.arm.includes('_fx')?'Rates + dollar':'Rates')+' · '+(row.arm.endsWith('10')?'10':'3')+'-day delay';panel.append(h);bar(panel,'Relative error (%)',(100+row.mse_change_vs_price_percent).toFixed(1),max);const p=document.createElement('p');p.textContent=row.arm==='price_only'?'Reference forecast':Math.abs(row.mse_change_vs_price_percent).toFixed(1)+'% '+(row.mse_change_vs_price_percent>0?'more':'less')+' squared error than prices alone';panel.append(p);box.append(panel);}
    };select.onchange=draw;draw();
  }catch(error){el('macro-outcomes').textContent='Macro forecast results unavailable.';}}
  macroOutcomes();
  const payrollPanel=document.createElement('section');payrollPanel.id='payroll-forecast-panel';
  payrollPanel.innerHTML='<h2>Employment context: a small, uncertain difference</h2><p>Weekly forecasts use historical payroll growth after an assumed month-end delay. Lower error is better. Compare large-miss sensitivity (squared error) with typical miss size (absolute error).</p><label>Comparison <select id="payroll-reference" aria-label="Payroll forecast reference"><option value="price_only">Price model</option><option value="training_mean">Past average return</option></select></label> <label>Uncertainty blocks <select id="payroll-block" aria-label="Payroll uncertainty block length"><option value="20">20 trading sessions</option><option value="60">60 trading sessions</option></select></label><div id="payroll-errors" class="visual-grid"></div><p class="visual-note">Dots show observed error differences; lines show descriptive 95% resampling ranges. A range crossing zero does not establish improvement. Blocks retain some dependence between overlapping forecasts. This does not account for all model selection or future regime changes, and no commissions, taxes or trading returns are modeled here.</p>';
  macroPanel.after(payrollPanel);
  async function payrollOutcomes(){try{
    const responses=await Promise.all(['payroll_forecast.json','payroll_uncertainty.json'].map(url=>fetch(url,{cache:'no-store'})));
    if(responses.some(r=>!r.ok)){payrollPanel.hidden=true;return;}
    const [data,uncertainty]=await Promise.all(responses.map(r=>r.json()));payrollPanel.hidden=false;
    const draw=()=>{
      const reference=el('payroll-reference').value,block=Number(el('payroll-block').value);
      const base=data.results.find(r=>r.year==='all'&&r.arm===reference);
      const rows=uncertainty.results.filter(r=>r.reference===reference&&r.block_sessions===block);
      const box=el('payroll-errors');box.replaceChildren();
      for(const arm of [...new Set(rows.map(r=>r.arm))]){
        const panel=document.createElement('div');panel.className='visual-panel';
        const h=document.createElement('h3');h.textContent='Payroll · '+(arm.endsWith('31')?'31 days':'1 day')+' after month end';panel.append(h);
        for(const row of rows.filter(r=>r.arm===arm)){
          const scale=100/base[row.metric];const low=row.lower*scale,high=row.upper*scale,mean=row.mean_difference*scale;
          const extent=Math.max(1,Math.abs(low),Math.abs(high))*1.15;
          const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 360 52');svg.setAttribute('role','img');
          const label=row.metric==='mse'?'Squared error':'Absolute error';
          svg.setAttribute('aria-label',label+': '+mean.toFixed(2)+' percent difference; range '+low.toFixed(2)+' to '+high.toFixed(2)+' percent');
          const x=value=>180+value/extent*150;
          for(const [x1,x2,y1,y2,color] of [[30,330,26,26,'#536273'],[180,180,6,46,'#ffffff'],[x(low),x(high),26,26,'#8d9fb5']]){
            const line=document.createElementNS(ns,'line');for(const [key,value] of Object.entries({x1,x2,y1,y2,stroke:color,'stroke-width':color==='#8d9fb5'?5:1}))line.setAttribute(key,value);svg.append(line);
          }
          const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x(mean));dot.setAttribute('cy','26');dot.setAttribute('r','5');dot.setAttribute('fill','#7ad5c1');svg.append(dot);
          const p=document.createElement('p');p.textContent=label+': '+mean.toFixed(2)+'% versus reference';panel.append(p,svg);
          const note=document.createElement('p');note.className='visual-note';note.textContent='Range '+low.toFixed(2)+'% to '+high.toFixed(2)+'%; white line = no difference. Each chart has its own scale.';panel.append(note);
        }
        box.append(panel);
      }
    };el('payroll-reference').onchange=draw;el('payroll-block').onchange=draw;draw();
  }catch(error){payrollPanel.hidden=false;el('payroll-errors').textContent='Employment forecast comparison unavailable.';}}
  payrollOutcomes();
  const replayPanel=document.createElement('section');replayPanel.id='trajectory-replay-panel';
  replayPanel.innerHTML='<h2>Different trading paths through the same history</h2><p id="replay-method">Four independent policy samples replay each artificial market scenario. Each path is compared with the other three paths’ net economic results. The agent can Hold or place orders every five minutes; no path is forced to hold.</p><div class="visual-stage">Same market → four different action paths → compare complete after-cost outcomes → one policy update</div><div id="replay-trials" class="visual-grid"></div><p id="replay-provenance" class="visual-note"></p>';
  view.prepend(replayPanel);
  async function replayOutcomes(){try{
    const response=await fetch('context_trajectory_replay.json',{cache:'no-store'});if(!response.ok){replayPanel.hidden=true;return;}
    const data=await response.json();replayPanel.hidden=false;el('replay-method').textContent=data.baseline==='hold'?'Independent policy paths replay each artificial market scenario. Their economic returns are compared with a separate Hold-only reference path. Reference actions never train or constrain the policy; sampled paths remain free to trade.':'Independent policy paths replay each artificial market scenario. Each path is compared with the other sampled paths’ net economic results. The agent remains free to Hold or trade every five minutes.';const box=el('replay-trials');box.replaceChildren();
    if(data.credit_mode==='reward_to_go')el('replay-method').textContent='Each decision learns from economic rewards still ahead of it, compared with independent paths through the same scenario. A gain already earned no longer reinforces later buy/sell decisions. The total economic objective is unchanged; Hold is never forced.';
    if(data.timing==='variable')el('replay-method').textContent+=' Training now varies the hidden future shock time across four response windows. This changes the artificial task, not the reward. The checkpoint checks below still use the original fixed timing; a separate matched grid evaluates response speed.';
    for(const trial of data.trials){
      const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent='Seed '+trial.seed+' · '+trial.status;panel.append(h);
      const budget=data.updates_per_seed*data.groups*data.replicas*70;
      bar(panel,'New training transitions',trial.steps,budget);
      const text=document.createElement('p');text.textContent=trial.new_optimizer_updates+' / '+data.updates_per_seed+' policy updates · '+(trial.history||[]).reduce((n,r)=>n+r.completed_episodes.length,0)+' complete episodes. Each episode contains 70 five-minute decisions. '+(trial.reference_steps||0)+' extra reference transitions are excluded from policy-training steps.';panel.append(text);
      const points=(trial.history||[]).map(row=>[row.update,row.mean_orders]);
      if(points.length>1){
        const max=Math.max(1,...points.map(p=>p[1]));const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 360 145');svg.setAttribute('role','img');svg.setAttribute('aria-label','Training filled orders per episode; zero to '+max.toFixed(1)+' orders, across '+points.length+' updates');
        const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>(20+320*p[0]/data.updates_per_seed)+','+(125-110*p[1]/max)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#7ad5c1');line.setAttribute('stroke-width','2');svg.append(line);panel.append(svg);
        const note=document.createElement('p');note.className='visual-note';note.textContent='Training filled orders per episode · vertical scale 0–'+max.toFixed(1)+' · horizontal scale 0–'+data.updates_per_seed+' updates. Market scenarios vary between updates; this curve is not validation.';panel.append(note);
      }
      const latest=(trial.evaluation_history||[]).slice(-1)[0];const assessed=trial.after||(latest&&latest.evaluation);
      if(assessed){const result=document.createElement('p');result.textContent=(trial.after?'Final budget':'Checkpoint at update '+latest.update)+' · reused diagnostic cases: '+assessed.exited_before_drop+'/'+assessed.adverse+' timely exits; '+assessed.retained_before_rise+'/'+assessed.favorable+' favorable holdings retained; '+assessed.flat_no_orders+'/'+assessed.flat+' flat cases without orders. Compare with additional greedy and sampled checks below, checking their source run.';panel.append(result);}
      if((trial.evaluation_history||[]).length){const details=document.createElement('details');const title=document.createElement('summary');title.textContent='All saved checkpoint checks';details.append(title);for(const checkpoint of trial.evaluation_history){const e=checkpoint.evaluation;const p=document.createElement('p');p.textContent='Update '+checkpoint.update+': '+e.exited_before_drop+'/'+e.adverse+' exits, '+e.retained_before_rise+'/'+e.favorable+' favorable retained, '+e.flat_no_orders+'/'+e.flat+' flat without trades; '+e.mean_orders.toFixed(2)+' orders/session.';details.append(p);}panel.append(details);}
      box.append(panel);
    }
    el('replay-provenance').textContent='Run '+data.run_id+' · '+data.status+' · source '+data.source_run+'. Complete means the fixed budget finished, not that the agent learned successfully. No learned critic or reward bonuses. This has fewer optimizer updates than earlier PPO studies and is not an isolated algorithm comparison.';
  }catch(error){el('replay-trials').textContent='Trajectory replay telemetry unavailable.';}}
  replayOutcomes();setInterval(replayOutcomes,15000);
  const validationPanel=document.createElement('section');validationPanel.innerHTML='<h2>Do the behaviors survive additional scenarios?</h2><p>Frozen models face another set of artificial price paths. Compare choosing the most likely action with sampling from the learned probabilities. A policy that looks restrained in the first mode may still trade frequently in the second.</p><label>Action selection <select id="validation-mode" aria-label="Validation action selection"><option value="greedy">Most likely action</option><option value="sampled">Sample learned probabilities</option><option value="news_hidden">Most likely action, news hidden</option></select></label><div id="validation-outcomes" class="visual-grid"></div><p id="validation-provenance" class="visual-note"></p>';
  responseStudy.after(validationPanel);
  async function validationOutcomes(){try{const r=await fetch('context_validation.json',{cache:'no-store'});if(!r.ok){validationPanel.hidden=true;return;}const d=await r.json();validationPanel.hidden=false;
    const draw=()=>{const mode=el('validation-mode').value;const box=el('validation-outcomes');box.replaceChildren();
      for(const t of d.trials){const e=t[mode];if(!e)continue;const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent='Seed '+t.seed+' · '+(d.algorithm&&d.algorithm.startsWith('REINFORCE')?'Trajectory replay':(t.critic_baseline?(t.critic_baseline==='zero'?'No learned baseline':'Learned baseline'):(t.event_response?'Added event memory':'Original inputs')));panel.append(h);
        for(const [label,key,total] of [['Timely exits','exits','adverse'],['Kept favorable holdings','retained','favorable'],['No trades in flat cases','flat_no_orders','flat']]){const p=document.createElement('p');p.textContent=label+': '+e[key]+' / '+e[total];panel.append(p);bar(panel,'Passed (%)',e[total]?Math.round(100*e[key]/e[total]):0,100);}
        const p=document.createElement('p');p.textContent=e.mean_orders.toFixed(1)+' orders per session';panel.append(p);box.append(panel);
      }
      el('validation-provenance').textContent='Run '+d.run_id+' · '+d.status+' · source '+d.source_run+'. '+d.cases+' '+d.limits+' Sampled results use a smaller scenario subset repeated twice; percentages are descriptive, not independent significance tests.';
    };el('validation-mode').onchange=draw;draw();
  }catch(error){el('validation-outcomes').textContent='Additional-scenario results unavailable.';}}
  validationOutcomes();
  const baselinePanel=document.createElement('section');baselinePanel.innerHTML='<h2>Current test: is the learned value baseline helping?</h2><p>Both arms start with the same action probabilities and unchanged trading costs. One learns future account value; the other uses complete episode returns without a learned value baseline. Removing the value loss also changes shared-network gradients, so this is a diagnostic comparison.</p><div id="baseline-progress" class="visual-grid"></div><p class="visual-note">This does not force holding or add reward bonuses. It is an artificial behavior test, not a market strategy. A completed training budget does not mean the policy has learned successfully.</p>';view.prepend(baselinePanel);
  async function baselineProgress(){try{const r=await fetch('context_value_baseline.json',{cache:'no-store'});if(!r.ok){baselinePanel.hidden=true;return;}const d=await r.json();baselinePanel.hidden=false;const box=el('baseline-progress');box.replaceChildren();
    for(const t of d.trials){const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent='Seed '+t.seed+' · '+(t.critic_baseline==='zero'?'No learned baseline':'Learned baseline');panel.append(h);bar(panel,t.status+' · training steps',t.steps,d.new_physical_step_budget);if(t.after){const p=document.createElement('p');p.textContent=t.after.exited_before_drop+'/'+t.after.adverse+' timely exits; '+t.after.retained_before_rise+'/'+t.after.favorable+' favorable holdings retained; '+t.after.flat_no_orders+'/'+t.after.flat+' flat cases without orders; '+t.after.mean_orders.toFixed(1)+' orders/session.';panel.append(p);}box.append(panel);}
  }catch(error){el('baseline-progress').textContent='Value-baseline report unavailable.';}}
  baselineProgress();setInterval(baselineProgress,15000);
  // Give completed behavior checks the same visual prominence as training progress.
  const responseGrid=document.createElement('div');responseGrid.className='visual-grid';responseStudy.append(responseGrid);
  async function responseOutcomes(){try{
    const r=await fetch('context_event_response.json',{cache:'no-store'});if(!r.ok)return;const d=await r.json();responseGrid.replaceChildren();
    for(const t of d.trials){if(!t.after)continue;const e=t.after;const panel=document.createElement('div');panel.className='visual-panel';
      const h=document.createElement('h3');h.textContent='Seed '+t.seed+' · '+(t.event_response?'Added event memory':'Original inputs');panel.append(h);
      for(const [label,key,total] of [['Timely exits','exited_before_drop','adverse'],['Kept favorable holdings','retained_before_rise','favorable'],['No unnecessary flat-market trades','flat_no_orders','flat']]){
        const caption=document.createElement('p');caption.textContent=label+' · '+e[key]+' of '+e[total];panel.append(caption);bar(panel,'Passed (%)',e[total]?Math.round(100*e[key]/e[total]):0,100);
      }
      const note=document.createElement('p');note.className='visual-note';note.textContent=e.mean_orders.toFixed(1)+' filled orders per session. Taller bars mean more cases passed; all three behaviors matter. These are reused artificial diagnostic cases, not independent market validation.';panel.append(note);responseGrid.append(panel);
    }
  }catch(error){responseGrid.textContent='Outcome charts unavailable.';}}
  refresh().then(criticRefresh);unitsRefresh();creditRefresh();flatRefresh();responseRefresh();responseOutcomes();setInterval(()=>{refresh().then(criticRefresh);unitsRefresh();creditRefresh();flatRefresh();responseRefresh();responseOutcomes();},15000);
  // Keep the newest learner and its validation together; preserve older studies.
  const previousStudies=document.createElement('details');const previousTitle=document.createElement('summary');
  previousTitle.textContent='Earlier PPO learning studies and diagnostic curves';previousStudies.append(previousTitle);
  for(const section of [baselinePanel,responseStudy,el('visual-verdict').closest('section'),el('visual-cases').closest('section'),el('visual-critic').closest('section')])previousStudies.append(section);
  view.append(previousStudies);view.prepend(replayPanel);replayPanel.after(validationPanel);
  baselinePanel.querySelector('h2').textContent='Earlier comparison: did the learned value baseline help?';
  setInterval(validationOutcomes,15000);
  const timingPanel=document.createElement('section');timingPanel.id='timing-validation';
  timingPanel.innerHTML='<h2>Did it memorize when the price moves?</h2><p>The earlier, longer replay models face the same artificial news, with the price jump moved earlier or later. This checks timing sensitivity while preserving the original timing as a control.</p><div id="timing-results" class="visual-grid"></div><p id="timing-source" class="visual-note"></p>';
  validationPanel.after(timingPanel);
  async function timingOutcomes(){try{
    const response=await fetch('context_timing.json',{cache:'no-store'});if(!response.ok){timingPanel.hidden=true;return;}
    const data=await response.json();const box=el('timing-results');box.replaceChildren();
    for(const seed of [...new Set(data.trials.map(t=>t.seed))]){
      const panel=document.createElement('div');panel.className='visual-panel';const title=document.createElement('h3');title.textContent='Longer replay · seed '+seed;panel.append(title);
      for(const row of data.trials.filter(t=>t.seed===seed)){
        const minutes=row.jump_index*5;const p=document.createElement('p');p.textContent='Shock '+minutes+' minutes after session start'+(row.jump_index===50?' (original timing)':'');panel.append(p);
        bar(panel,'Timely exits (%)',row.adverse?Math.round(100*row.exits/row.adverse):0,100);
        const note=document.createElement('p');note.className='visual-note';note.textContent=row.exits+'/'+row.adverse+' exits · '+row.retained+'/'+row.favorable+' favorable holdings retained · '+row.flat_no_orders+'/'+row.flat+' flat cases without trades.';panel.append(note);
      }box.append(panel);
    }
    el('timing-source').textContent='Source '+data.source_run+' · timing run '+data.run_id+' · '+data.status+'. Same 64 cases repeated at three timings, not 192 independent cases. Greedy actions only. The other seed and previously observed excessive sampled trading remain failures; this does not establish market or language generalization.';
  }catch(error){el('timing-results').textContent='Timing validation unavailable.';}}
  timingOutcomes();
  const ordersPanel=document.createElement('section');ordersPanel.id='order-audit';
  ordersPanel.innerHTML='<h2>Are those trades actually useful?</h2><p>The stronger model sometimes buys and sells the same shares back and forth. These charts expose actual orders and their costs, even when an episode passes its simple behavior check.</p><div id="order-audit-summary" class="visual-grid"></div><p><label>Training seed <select id="order-audit-seed" aria-label="Order audit training seed"></select></label> <label>Scenario <select id="order-audit-case" aria-label="Order audit scenario"></select></label></p><p id="order-audit-description"></p><div id="order-audit-charts" class="visual-grid"></div><p id="order-audit-details" aria-live="polite"></p><p id="order-audit-source" class="visual-note"></p>';
  view.prepend(ordersPanel);
  let orderData=null;
  function orderChart(title,points,trace,note){
    const panel=document.createElement('div');panel.className='visual-panel';
    const heading=document.createElement('h3');heading.textContent=title;panel.append(heading);
    const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');
    svg.setAttribute('viewBox','0 0 480 220');svg.setAttribute('role','img');svg.setAttribute('aria-label',title+' across the simulated session');
    let ymin=Math.min(0,...points.map(p=>p[1])),ymax=Math.max(1,...points.map(p=>p[1]));
    const x=i=>55+405*i/(points.length-1),y=v=>175-145*(v-ymin)/(ymax-ymin);
    const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map((p,i)=>x(i)+','+y(p[1])).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#7ad5c1');line.setAttribute('stroke-width','2');svg.append(line);
    for(let i=0;i<trace.length;i++){const event=trace[i];if(event.status!=='filled')continue;
      const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x(i+1));dot.setAttribute('cy',y(points[i+1][1]));dot.setAttribute('r','3');dot.setAttribute('fill',event.side==='buy'?'#80bfff':'#ffab91');
      const tip=document.createElementNS(ns,'title');tip.textContent=event.side+' '+event.quantity+' '+event.symbol+' @ $'+Number(event.price).toFixed(2)+' · fee $'+Number(event.costs.total).toFixed(2)+' · '+event.execution_time;dot.append(tip);svg.append(dot);
    }
    const axis=document.createElementNS(ns,'path');axis.setAttribute('d','M55 25V175H460');axis.setAttribute('stroke','#738192');axis.setAttribute('fill','none');svg.append(axis);
    for(const [a,b,text] of [[2,35,ymax.toFixed(0)],[2,175,ymin.toFixed(0)],[55,198,'First decision'],[345,198,'Session end']]){const label=document.createElementNS(ns,'text');label.setAttribute('x',a);label.setAttribute('y',b);label.setAttribute('fill','#a8b6c5');label.setAttribute('font-size','12');label.textContent=text;svg.append(label);}
    panel.append(svg);const caption=document.createElement('p');caption.className='visual-note';caption.textContent=note+' Blue dots: buys. Orange dots: sells. Hover a dot for the actual order.';panel.append(caption);return panel;
  }
  function renderOrderCase(){
    const trial=orderData.trials.find(t=>String(t.seed)===el('order-audit-seed').value);
    const row=trial.rows.find(r=>String(r.seed)===el('order-audit-case').value);if(!row)return;
    el('order-audit-description').textContent=(row.flat?'Flat prices / no news':row.kind+' event · '+row.role+' of '+row.target+' · authored '+(row.direction>0?'rise':'drop'))+'. Starting with 150 shares of each of two stocks in a hypothetical $100,000 IRA.';
    const charts=el('order-audit-charts');charts.replaceChildren();
    charts.append(orderChart('Target shares held',[[0,150],...row.trace.map((e,i)=>[i+1,e.target_shares])],row.trace,'Shows actual holdings after each decision; no target-allocation rounding is applied by this plot.'));
    const excess=[[0,0],...row.trace.map((e,i)=>[i+1,e.wealth-(e.observed_index+1>=row.jump?row.hold_final_wealth:row.starting_wealth)])];
    charts.append(orderChart('Wealth above simply holding ($)',excess,row.trace,'Same starting portfolio and price path. Actual simulated trading fees included. This one-session authored shock is not a market return forecast.'));
    el('order-audit-details').textContent=row.orders+' filled orders · '+row.audit.buy_orders+' buys / '+row.audit.sell_orders+' sells · $'+row.audit.fees_dollars.toFixed(2)+' in fees · '+row.audit.same_price_round_trips.length+' nonoverlapping equal-price, equal-quantity round trips, costing $'+row.audit.round_trip_fees_dollars.toFixed(2)+'. Ending wealth versus Hold: $'+row.excess_wealth_dollars.toFixed(2)+'.';
  }
  function chooseOrderSeed(){const trial=orderData.trials.find(t=>String(t.seed)===el('order-audit-seed').value);const select=el('order-audit-case');select.replaceChildren();
    // Most orders first makes the diagnostic failure visible; this is not model selection.
    for(const row of [...trial.rows].sort((a,b)=>b.orders-a.orders||a.seed-b.seed)){const option=document.createElement('option');option.value=row.seed;option.textContent=row.seed+' · '+row.orders+' orders · '+(row.flat?'flat':row.direction>0?'favorable':'adverse');select.append(option);}renderOrderCase();}
  el('order-audit-seed').addEventListener('change',chooseOrderSeed);el('order-audit-case').addEventListener('change',renderOrderCase);
  async function orderAudit(){try{
    const response=await fetch('context_order_audit.json',{cache:'no-store'});if(!response.ok){ordersPanel.hidden=true;return;}
    orderData=await response.json();if(!orderData.trials.length){el('order-audit-description').textContent='Replaying completed cases to inspect actual orders…';return;}
    const summary=el('order-audit-summary');summary.replaceChildren();const select=el('order-audit-seed');select.replaceChildren();
    for(const trial of orderData.trials){const option=document.createElement('option');option.value=trial.seed;option.textContent=trial.seed;select.append(option);
      const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent='Seed '+trial.seed;panel.append(h);
      const p=document.createElement('p');p.textContent=trial.summary.all.mean_orders.toFixed(1)+' orders per session · '+trial.summary.all.round_trips+' equal-price round trips across '+trial.summary.all.episodes+' cases.';panel.append(p);summary.append(panel);}
    select.value=String(orderData.trials[orderData.trials.length-1].seed);chooseOrderSeed();
    el('order-audit-source').textContent='Frozen model run '+orderData.model_run+' · exact replay of economic validation '+orderData.source_run+' · audit '+orderData.run_id+' · '+orderData.status+'. Both seeds retained. Round-trip counts describe executed orders; they do not change rewards or force the learner to hold.';
  }catch(error){el('order-audit-description').textContent='Order audit unavailable; no results can be displayed.';}}
  orderAudit();
  const creditComparison=document.createElement('section');creditComparison.id='credit-comparison';
  creditComparison.innerHTML='<h2>Can better credit assignment reduce wasteful trading?</h2><p>Two matched training runs start from the same models. The control credits every decision with the whole episode’s result. The alternative credits each decision only with rewards still ahead. Both maximize the same after-cost wealth; neither forces Hold.</p><p><label>Additional validation <select id="credit-comparison-mode" aria-label="Credit comparison action selection"><option value="greedy">Most likely action</option><option value="sampled">Sample learned probabilities</option><option value="news_hidden">Most likely action, news hidden</option></select></label></p><div id="credit-comparison-results" class="visual-grid"></div><p id="credit-comparison-source" class="visual-note"></p>';
  view.prepend(creditComparison);let creditComparisonData=null;
  function renderCreditComparison(){
    const data=creditComparisonData;if(!data)return;const box=el('credit-comparison-results');box.replaceChildren();
    for(const arm of data.arms){const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent=arm.credit_mode==='trajectory'?'Control · whole episode':'Alternative · remaining rewards';panel.append(h);
      const progress=document.createElement('p');progress.textContent=arm.status==='queued'?'Queued; no result yet.':'Training: '+arm.status+(arm.validation_status?' · validation: '+arm.validation_status:' · additional validation pending');panel.append(progress);
      for(const trial of arm.trials){const title=document.createElement('h4');title.textContent='Seed '+trial.seed+' · '+trial.updates+'/'+data.plan.updates_per_seed+' updates';panel.append(title);
        const evaluation=(trial.validation||{})[el('credit-comparison-mode').value];
        if(evaluation){
          for(const [name,count,total] of [['Timely exits',evaluation.exits,evaluation.adverse],['Favorable holdings kept',evaluation.retained,evaluation.favorable],['Flat cases without trades',evaluation.flat_no_orders,evaluation.flat]]){
            const p=document.createElement('p');p.textContent=name+': '+count+' / '+total;panel.append(p);bar(panel,'Passed (%)',total?100*count/total:0,100);}
          const p=document.createElement('p');p.textContent=evaluation.mean_orders.toFixed(2)+' filled orders per session';panel.append(p);
        }else{const p=document.createElement('p');p.textContent='No completed additional result in this mode yet.';panel.append(p);}
      }
      if(arm.error||arm.validation_error){const p=document.createElement('p');p.className='visual-status';p.textContent=arm.error||arm.validation_error;panel.append(p);}box.append(panel);
    }
    el('credit-comparison-source').textContent='Comparison '+data.run_id+' · '+data.status+' · snapshot '+data.updated_at+'. Same '+data.plan.updates_per_seed+' updates per seed, groups and starting models. Greedy/news-hidden: 64 cases; sampled: first 32 cases twice. Same authored templates, not real-market validation. A completed budget is not evidence of convergence. Results remain visible for both seeds and arms.';
  }
  el('credit-comparison-mode').addEventListener('change',renderCreditComparison);
  async function creditComparisonRefresh(){try{const response=await fetch('credit_comparison.json',{cache:'no-store'});if(!response.ok){creditComparison.hidden=true;return;}creditComparison.hidden=false;creditComparisonData=await response.json();renderCreditComparison();}catch(error){el('credit-comparison-results').textContent='Paired comparison snapshot unavailable.';}}
  creditComparisonRefresh();setInterval(creditComparisonRefresh,15000);
  const portfolioDetails=document.createElement('details');portfolioDetails.id='portfolio-sensitivity';
  portfolioDetails.innerHTML='<summary>Do different starting balances or holdings change the result?</summary><p>The same frozen models face five starting portfolios on the same 32 artificial cases. Bars compare actual order counts, not investment returns.</p><label>Training seed <select id="portfolio-sensitivity-seed" aria-label="Portfolio sensitivity seed"><option>42</option><option selected>43</option></select></label><div id="portfolio-sensitivity-results" class="visual-grid"></div><p id="portfolio-sensitivity-note" class="visual-note"></p>';
  creditComparison.append(portfolioDetails);let portfolioData=null;
  function portfolioSensitivity(){if(!portfolioData)return;const seed=Number(el('portfolio-sensitivity-seed').value),box=el('portfolio-sensitivity-results');box.replaceChildren();
    const selected=portfolioData.trials.filter(t=>t.seed===seed),maximum=Math.max(1,...selected.map(t=>t.mean_orders));
    for(const config of portfolioData.plan.configurations){const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent='$'+config.starting_cash.toLocaleString()+' · '+config.opening_shares[0]+' / '+config.opening_shares[1]+' shares';panel.append(h);
      for(const mode of ['trajectory','reward_to_go']){const row=selected.find(t=>t.configuration===config.name&&t.credit_mode===mode);if(!row)continue;
        bar(panel,mode==='trajectory'?'Whole episode · orders':'Remaining rewards · orders',row.mean_orders.toFixed(2),maximum,mode==='trajectory');
        const p=document.createElement('p');p.className='visual-note';p.textContent=(mode==='trajectory'?'Control: ':'Alternative: ')+row.exits+'/'+row.adverse+' timely exits; '+row.retained+'/'+row.favorable+' favorable positions retained; '+row.flat_no_orders+'/'+row.flat+' flat cases without trades.';panel.append(p);
      }box.append(panel);
    }
    el('portfolio-sensitivity-note').textContent='All bars share the same scale within the selected seed. Capital includes the starting stock purchases; share counts refer to A and B. Original starting portfolios exactly reproduce prior validation. Changing a known account state is not new language or market evidence. Source paired run '+portfolioData.plan.source_run+' · portfolio run '+portfolioData.run_id+' · '+portfolioData.status+'.';
  }
  el('portfolio-sensitivity-seed').addEventListener('change',portfolioSensitivity);
  fetch('context_portfolios.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json();}).then(data=>{portfolioData=data;portfolioSensitivity();}).catch(()=>{portfolioDetails.hidden=true;});
  const timingTraining=document.createElement('section');timingTraining.id='timing-training';
  timingTraining.innerHTML='<h2>Can the agent learn to react sooner?</h2><p>Training used to allow many chances to exit before a predictable late price move. We now compare that training with uncertain response windows, including just one chance to trade. The model cannot see when the future move will happen. Costs and economic rewards stay unchanged.</p><p><label>Action selection <select id="timing-training-mode" aria-label="Timing training action selection"><option value="greedy">Most likely action</option><option value="sampled">Sample learned probabilities</option></select></label> <label>Chances to act before the move <select id="timing-training-window" aria-label="Timing training response window"><option value="9">1 chance</option><option value="20">12 chances</option><option value="50">42 chances · original</option><option value="65">57 chances</option></select></label></p><div id="timing-training-results" class="visual-grid"></div><p id="timing-training-source" class="visual-note"></p>';
  view.prepend(timingTraining);let timingTrainingData=null;
  const priorCredit=document.createElement('details');priorCredit.id='prior-credit-study';const priorCreditTitle=document.createElement('summary');priorCreditTitle.textContent='Completed comparison: whole-episode versus remaining-reward credit';priorCredit.append(priorCreditTitle);creditComparison.before(priorCredit);priorCredit.append(creditComparison);priorCredit.open=true;
  const portfolioNote=document.createElement('p');portfolioNote.className='visual-note';timingTraining.append(portfolioNote);
  fetch('timing_portfolios.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{
    if(!data||data.status!=='complete')return;
    const sampled=data.trials.filter(r=>r.mode==='sampled'),counts=sampled.map(r=>r.mean_orders);
    portfolioNote.textContent='Additional frozen-policy check: 32 new synthetic cases across three starting portfolios, with 12 chances to act before the move. Most-likely-action behavior was similar across portfolio sizes, but sampled policies averaged '+Math.min(...counts).toFixed(1)+'–'+Math.max(...counts).toFixed(1)+' orders per session and repeatedly traded in no-opportunity cases. Portfolio size changes did not resolve excessive trading. This is evaluation only: '+data.policy_episodes+' policy episodes, zero training updates.';
  }).catch(()=>{portfolioNote.textContent='Additional portfolio check unavailable.';});
  const semanticNote=document.createElement('p');semanticNote.className='visual-note';
  semanticNote.textContent='News understanding check: frozen models handled reworded versions of the six training stories, but failed when a story kept the same category and relationship while its meaning reversed (for example, a supplier cutting rather than raising prices). Timely exits fell to 0–4 of 13 adverse cases. These models have not demonstrated reliable understanding of new news. This was a 288-episode authored simulation with no further training.';
  portfolioNote.after(semanticNote);
  const semanticGrid=document.createElement('div');semanticGrid.className='visual-grid';semanticNote.after(semanticGrid);
  fetch('event_transfer.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{
    if(!data||data.status!=='complete')return;
    for(const timing of ['fixed','variable'])for(const seed of [42,43]){
      const panel=document.createElement('div');panel.className='visual-panel';
      const title=document.createElement('h3');title.textContent=(timing==='fixed'?'Fixed timing':'Variable timing')+' · seed '+seed;panel.append(title);
      for(const [corpus,label] of [['original','Original stories'],['paraphrase','Same meaning, new wording'],['reversed_meaning','Opposite meaning, same category']]){
        const row=data.rows.find(r=>r.timing===timing&&r.seed===seed&&r.corpus===corpus);if(!row)continue;
        const text=document.createElement('p');text.textContent=label+': '+row.exits+'/'+row.adverse+' timely exits';panel.append(text);
        bar(panel,'Adverse cases exited (%)',100*row.exits/row.adverse,100);
        const detail=document.createElement('p');detail.className='visual-note';detail.textContent='Favorable holdings retained: '+row.retained+'/'+row.favorable+'. Average orders: '+row.mean_orders.toFixed(1)+'.';panel.append(detail);
      }semanticGrid.append(panel);
    }
    const note=document.createElement('p');note.className='visual-note';note.textContent='Separate text-only sanity check: with balanced positive/negative examples within each category, frozen text vectors classified 9/12 newly worded stories correctly; category-only classified 6/12. This tiny supervised check is not RL training or evidence of market returns. Source '+data.transfer_run+' · '+data.episodes+' episodes · '+data.physical_steps+' market steps · '+data.optimizer_updates+' training updates.';semanticGrid.after(note);
  }).catch(()=>{semanticGrid.textContent='Semantic diagnostic charts unavailable.';});
  function renderTimingTraining(){const data=timingTrainingData;if(!data)return;const box=el('timing-training-results');box.replaceChildren();
    for(const arm of data.arms){const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent=arm.timing==='fixed'?'Control · fixed late move':'Alternative · uncertain timing';panel.append(h);
      const p=document.createElement('p');p.textContent=arm.status==='queued'?'Queued; no result yet.':'Training: '+arm.status+(arm.validation_status?' · validation: '+arm.validation_status:' · validation pending');panel.append(p);
      for(const trial of arm.trials){const title=document.createElement('h4');title.textContent='Seed '+trial.seed+' · '+trial.updates+'/'+data.plan.updates_per_seed+' updates';panel.append(title);
        const row=(trial.validation||[]).find(r=>r.mode===el('timing-training-mode').value&&r.jump_index===Number(el('timing-training-window').value));
        if(row){for(const [name,count,total] of [['Timely exits',row.exits,row.adverse],['Favorable holdings retained',row.retained,row.favorable],['Flat cases without trades',row.flat_no_orders,row.flat]]){const label=document.createElement('p');label.textContent=name+': '+count+' / '+total;panel.append(label);bar(panel,'Passed (%)',total?100*count/total:0,100);}const orders=document.createElement('p');orders.textContent=row.mean_orders.toFixed(2)+' filled orders per session';panel.append(orders);}
        else{const pending=document.createElement('p');pending.textContent='This validation result is not ready yet.';panel.append(pending);}
      }
      if(arm.error||arm.validation_error){const error=document.createElement('p');error.className='visual-status';error.textContent=arm.error||arm.validation_error;panel.append(error);}box.append(panel);
    }
    el('timing-training-source').textContent='Comparison '+data.run_id+' · '+data.status+' · updated '+data.updated_at+'. Matched '+data.plan.updates_per_seed+' updates per seed and identical starting weights. Most-likely actions: 64 cases; sampled actions: first 32 cases twice. The uncertainty is in an authored simulation, not a verified model of news impacts. No market-performance claim.';
  }
  for(const id of ['timing-training-mode','timing-training-window'])el(id).addEventListener('change',renderTimingTraining);
  async function timingTrainingRefresh(){try{const response=await fetch('timing_training.json',{cache:'no-store'});if(!response.ok){timingTraining.hidden=true;return;}timingTraining.hidden=false;timingTrainingData=await response.json();if(!timingTraining.dataset.initialized){priorCredit.open=false;timingTraining.dataset.initialized='true';}renderTimingTraining();}catch(error){el('timing-training-results').textContent='Timing experiment snapshot unavailable.';}}
  timingTrainingRefresh();setInterval(timingTrainingRefresh,15000);
  const interestChecks=document.createElement('section');interestChecks.id='interest-checks';
  const featureInventory=document.createElement('section');featureInventory.id='feature-inventory';
  featureInventory.innerHTML=`<h2>What information can the agent see?</h2>
    <p>Code audit · September 13, 2026. These are available components, not a claim that every experiment uses every input. Real-data RL has not resumed.</p>
    <label>Explore an input group <select id="feature-group"></select></label>
    <div id="feature-detail" class="visual-panel" style="margin-top:12px"></div>
    <details><summary>How the relationship model extends Ripple</summary>
    <svg viewBox="0 0 720 130" role="img" aria-label="Conceptual flow: each company's price history and news form a stock representation; dated relationships exchange messages; account state informs Hold or an order" style="width:100%;max-width:900px">
      <g fill="none" stroke="currentColor"><rect x="5" y="25" width="175" height="70" rx="6"/><rect x="235" y="25" width="210" height="70" rx="6"/><rect x="500" y="25" width="210" height="70" rx="6"/><path d="M180 60 H228 M218 54 L228 60 L218 66 M445 60 H493 M483 54 L493 60 L483 66"/></g>
      <g fill="currentColor" text-anchor="middle" font-size="15"><text x="92" y="53">Company history</text><text x="92" y="76">+ available news</text><text x="340" y="53">Related-company messages</text><text x="340" y="76">correlation + dated links</text><text x="605" y="53">Account, lots and costs</text><text x="605" y="76">→ Hold or an order</text></g></svg>
    <p>Conceptual architecture, not measured performance. The current network exchanges one round of messages. Multiple rounds, relation-specific attention and delayed propagation are candidates to compare. No two-dimensional layout is required.</p></details>`;
  view.prepend(featureInventory);
  const featureGroups=[
    ['Price and volume','Implemented · shared representation','Dimensionless log returns, volatility-scaled returns, trailing volatility, candle returns/ranges, relative volume for matching times of day, return relative to the observed stock universe, clock time, elapsed time and missingness flags.','Default history: 32 five-minute observations, 32 completed daily observations and 26 completed weekly observations. Retained minute data is optional. Completed-period availability is checked against the exchange calendar. The universe average is not SPY or a sector benchmark.'],
    ['Relationships','Implemented · simple graph; real link feed incomplete','Trailing correlations over up to 20 sessions plus supplied directed competitor, supplier and customer links. Each company has a shared temporal encoder; related-company messages condition its order choices.','Current links require availability time and evidence, but there is no audited broad historical competitor/supply-chain dataset. One message-passing stage is implemented. Multi-hop propagation and learned edge attention have not been validated.'],
    ['News and price response','Implemented adapters · synthetic controlled tests','Multiple event types, affected-company roles, numeric changes or surprises when known, uncertainty, age, revision evidence, and frozen 768-dimensional contextual text vectors. An optional adapter records price response since publication.','The local FinBERT vector uses hidden representations, not only positive/negative sentiment. Automatic LLM fact extraction and historical news contamination controls remain incomplete. Authored demonstration events are not real-news trading results.'],
    ['Macro economy','Optional adapter · no macro RL result','Each supplied series can expose nine fields: level, period change, release age, observation-period age, revision flag, value/change/release availability, and staleness.','Exploratory real-data forecasting checked 2-year and 10-year Treasury yields, yield slope, rate changes, broad dollar movement and payroll vintages. No reliable improvement was established. Policy rates, unemployment, inflation, credit spreads and international risk are proposed additions, not a populated production feature set. Exact historical release values/times need validation.'],
    ['Portfolio and taxes','Implemented · scope varies by adapter','Account cash and buying power; position weight and gains; feasible order size, estimated commissions and volume participation; individual tax lots, holding age, long-term eligibility, wash-sale exposure, settlements and annual tax scenarios.','Combined interest, cash-dividend and plain overnight split accounting now has an opt-in adapter. Share units, dividend entitlement and replay have focused checks. Long training with these inputs has not run. Fractional cash-in-lieu, retained-minute split features and multi-year margin financing remain unsupported.'],
    ['Compound features to test','Research plan · not current training inputs','Start with small, interpretable interactions: momentum × volatility; news surprise × prior price response; sector-relative movement × unusual volume; rate change × company rate sensitivity; competitor news aggregated through dated graph links.','Screen feature groups on chronological held-out data with linear and tree models before expensive RL. Fit transforms and choose features only inside training windows; compare no-interaction, explicit-interaction and graph variants on identical dates. Forecast improvements must still survive trading costs and taxes.']
  ];
  const featureSelect=el('feature-group');
  featureGroups.forEach((group,index)=>{const option=document.createElement('option');option.value=index;option.textContent=group[0];featureSelect.append(option);});
  function renderFeatureGroup(){const group=featureGroups[Number(featureSelect.value)];const panel=el('feature-detail');panel.replaceChildren();for(const [tag,text] of [['h3',group[0]],['strong',group[1]],['p',group[2]],['p',group[3]]]){const node=document.createElement(tag);node.textContent=text;panel.append(node);}}
  featureSelect.addEventListener('change',renderFeatureGroup);renderFeatureGroup();
  const compoundScreen=document.createElement('section');compoundScreen.id='compound-screen';
  compoundScreen.innerHTML='<h2>Do compound features improve forecasts?</h2><p>Real daily data, selected stock sample. Compare basic price/volume inputs with training-selected pair products. This predicts market quantities; it does not simulate investing returns.</p><label>Forecast <select id="compound-target"><option value="return">Five-session return</option><option value="volatility">Five-session volatility (RMS daily return)</option><option value="downside">Five-session downside (RMS negative daily return)</option></select></label> <label>Period <select id="compound-period"><option value="all">All evaluated dates</option></select></label><div id="compound-bars" class="visual-grid"></div><p id="compound-source" class="visual-note"></p>';
  featureInventory.after(compoundScreen);
  let compoundData=null;
  function renderCompounds(){if(!compoundData)return;const target=el('compound-target').value,period=el('compound-period').value;const rows=compoundData.results.filter(r=>r.target===target&&r.period===period);const baseline=rows.find(r=>r.arm==='stock_training_mean');if(!baseline)return;const box=el('compound-bars');box.replaceChildren();const names={training_mean:'Historical mean · all stocks',stock_training_mean:'Historical mean · each stock',ridge_base:'Linear · base inputs',ridge_compound:'Linear · added interactions',tree_base:'Tree · base inputs',tree_compound:'Tree · added interactions'};const max=Math.max(110,...rows.map(r=>100*r.mse/baseline.mse));for(const row of rows){const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent=names[row.arm];panel.append(h);const ratio=100*row.mse/baseline.mse;bar(panel,'Squared error (% of stock-specific mean)',ratio,max);const text=document.createElement('p');text.textContent=(ratio-100).toFixed(2)+'% error difference; lower is better. '+row.rows.toLocaleString()+' stock/date forecasts.';panel.append(text);box.append(panel);}el('compound-source').textContent='Run '+compoundData.run_id+' · '+compoundData.symbols_observed.length+'/'+compoundData.requested_symbols+' symbols; missing: '+compoundData.missing_symbols.join(', ')+'. '+compoundData.folds+' quarterly refits, 2022–2026; 756-session trailing training limit. 45 candidate pair products, 16 selected using training rows only. Baseline was strengthened after the first screen. Previously explored years, vendor-adjusted history and selected universe: exploratory, not an untouched test. Overlapping labels are dependent. No commissions, taxes, trades, macro or graph features in this comparison.';}
  el('compound-target').addEventListener('change',renderCompounds);el('compound-period').addEventListener('change',renderCompounds);
  async function refreshCompounds(){try{const response=await fetch('compound_screen.json',{cache:'no-store'});if(!response.ok){compoundScreen.hidden=true;return;}compoundData=await response.json();compoundScreen.hidden=false;if(!compoundScreen.dataset.ready){for(const year of [...new Set(compoundData.results.map(r=>r.period))].filter(y=>y!=='all').sort()){const option=document.createElement('option');option.value=year;option.textContent=year;el('compound-period').append(option);}compoundScreen.dataset.ready='true';}renderCompounds();}catch(error){el('compound-source').textContent='Forecast screen unavailable.';}}
  refreshCompounds();
  const graphScreen=document.createElement('details');graphScreen.id='graph-screen';
  graphScreen.innerHTML='<summary>Do related-stock movements add information?</summary><div class="visual-grid" id="graph-screen-results"></div><p class="visual-note">Exploratory linear forecast test, not neural graph training or portfolio performance. Top-five historical correlation links are fitted before each quarter. Compare ordinary features with related-stock messages, one-session-delayed messages, and randomly reassigned links. Same previously studied 31 stocks and dates; no competitor data, macro or news. Error differences below zero are better. Small differences with uncertainty spanning zero are inconclusive.</p>';
  compoundScreen.append(graphScreen);
  async function refreshGraphScreen(){try{const response=await fetch('graph_screen.json',{cache:'no-store'});if(!response.ok){graphScreen.hidden=true;return;}const data=await response.json();if(data.status!=='complete'){graphScreen.hidden=true;return;}const box=el('graph-screen-results');box.replaceChildren();for(const target of ['return','volatility','downside']){const panel=document.createElement('div');panel.className='visual-panel';const heading=document.createElement('h3');heading.textContent=target==='return'?'Future return':target==='volatility'?'Future volatility':'Future downside';panel.append(heading);for(const row of data.results.filter(r=>r.target===target)){const text=document.createElement('p');text.textContent=({neighbors:'Related stocks',lagged_neighbors:'One-session delay',shuffled_neighbors:'Shuffled links'})[row.arm]+': '+row.mse_change_percent.toFixed(2)+'% squared-error change; 20-session block range '+row.interval20.map(v=>v.toFixed(2)+'%').join(' to ')+'.';panel.append(text);}box.append(panel);}}catch(error){el('graph-screen-results').textContent='Graph comparison unavailable.';}}
  refreshGraphScreen();
  const macroRisk=document.createElement('details');macroRisk.id='macro-risk';
  macroRisk.innerHTML='<summary>Do rates, currencies and compound inputs improve stock forecasts?</summary><p>Retrospective sensitivity test: two- and ten-year Treasury yields, yield-curve slope, their changes and broad-dollar movement. Four fixed interactions combine these with stock returns or volatility. Values use current revisions with assumed 3/10-day delays; original publication timing is not certified. Shorter bars are better; 100% matches price-only inputs.</p><div class="visual-grid" id="macro-risk-results"></div><p class="visual-note">Same 31-stock sample and 19 quarterly refits as the basic feature screen. These variants increased aggregate forecast error. This does not establish that macro information is useless: the chosen transforms, model and data timing are limited. No unemployment, news, trades or tax returns are modeled here.</p>';
  graphScreen.after(macroRisk);
  async function refreshMacroRisk(){try{const response=await fetch('macro_risk.json',{cache:'no-store'});if(!response.ok){macroRisk.hidden=true;return;}const data=await response.json();if(data.status!=='complete'||data.mode!=='retrospective_sensitivity'){macroRisk.hidden=true;return;}const box=el('macro-risk-results');box.replaceChildren();for(const target of ['return','volatility','downside']){const panel=document.createElement('div');panel.className='visual-panel';const title=document.createElement('h3');title.textContent=target;panel.append(title);const rows=data.results.filter(r=>r.target===target),max=Math.max(120,...rows.map(r=>100+r.mse_change_percent));bar(panel,'Price-only reference','100.00',max);for(const row of rows)bar(panel,({macro_3:'Macro · 3-day delay',interactions_3:'Plus interactions · 3 days',macro_10:'Macro · 10-day delay',interactions_10:'Plus interactions · 10 days'})[row.arm],(100+row.mse_change_percent).toFixed(2),max);box.append(panel);}}catch(error){el('macro-risk-results').textContent='Macro sensitivity results unavailable.';}}
  refreshMacroRisk();
  const positiveRisk=document.createElement('section');
  positiveRisk.innerHTML='<h3>Follow-up: can a different model use macro context?</h3><p>These small tree models predict nonnegative risk. Each receives 80 training rounds. This is inner validation on the second half of the selected year, not an outer test or trading return. Shorter bars mean less forecast error; 100% is the same tree model with stock inputs only.</p><label>Validation year <select id="positive-risk-year"><option value="2022">2021</option><option value="2023">2022</option><option value="2024">2023</option><option value="2025">2024</option></select></label><div id="positive-risk-bars" class="visual-grid"></div><p class="visual-note">Macro benefits are mixed across periods and risk measures. Inputs still use revised history and assumed delays. No best model or training checkpoint has been selected.</p>';
  macroRisk.append(positiveRisk);
  async function refreshPositiveRisk(){
    try{
      const response=await fetch('positive_macro.json',{cache:'no-store'});
      if(!response.ok){positiveRisk.hidden=true;return;}
      const data=await response.json();
      if(data.status!=='complete'){positiveRisk.hidden=true;return;}
      const draw=()=>{
        const year=Number(el('positive-risk-year').value),box=el('positive-risk-bars');
        box.replaceChildren();
        for(const target of ['volatility','downside']){
          const rows=data.results.filter(r=>r.year===year&&r.target===target);
          const panel=document.createElement('div');panel.className='visual-panel';
          const title=document.createElement('h4');title.textContent=target==='volatility'?'Overall price variability':'Downside price variability';panel.append(title);
          const max=Math.max(120,...rows.map(r=>100+r.change_vs_base_percent));
          for(const row of rows)bar(panel,({base:'Stock inputs only',macro_3:'Plus macro · 3-day delay',macro_10:'Plus macro · 10-day delay'})[row.arm],(100+row.change_vs_base_percent).toFixed(2),max);
          box.append(panel);
        }
      };
      el('positive-risk-year').addEventListener('change',draw);draw();
    }catch(error){el('positive-risk-bars').textContent='Positive-risk diagnostic unavailable.';}
  }
  refreshPositiveRisk();
  const positiveOuter=document.createElement('section');
  positiveOuter.innerHTML='<h4>Broader quarterly follow-up · 2022–2026</h4><p>The same fixed models were refitted each quarter. Across these longer, previously explored dates, macro inputs increased forecast error. The earlier inner-validation gains did not carry through. No model was promoted.</p><div id="positive-outer-bars" class="visual-grid"></div>';
  positiveRisk.prepend(positiveOuter);
  async function refreshPositiveOuter(){
    try{
      const response=await fetch('positive_macro_outer_audit.json',{cache:'no-store'});
      if(!response.ok){positiveOuter.hidden=true;return;}
      const data=await response.json(),box=el('positive-outer-bars');box.replaceChildren();
      for(const target of ['volatility','downside']){
        const panel=document.createElement('div');panel.className='visual-panel';
        const title=document.createElement('h4');title.textContent=target;panel.append(title);
        const rows=data.aggregate.filter(r=>r.target===target&&['base','macro_3','macro_10'].includes(r.arm));
        const max=Math.max(120,...rows.map(r=>100+r.change_vs_base_percent));
        for(const row of rows)bar(panel,({base:'Stock-only tree · 100% reference',macro_3:'Plus macro · 3-day delay',macro_10:'Plus macro · 10-day delay'})[row.arm],(100+row.change_vs_base_percent).toFixed(2),max);
        box.append(panel);
      }
    }catch(error){el('positive-outer-bars').textContent='Quarterly follow-up unavailable.';}
  }
  refreshPositiveOuter();
  const neuralGraph=document.createElement('details');neuralGraph.id='neural-graph';
  neuralGraph.innerHTML='<summary>Neural relationship test · two training seeds</summary><p>Eight fixed training epochs per annual fold, 2022–2025. Bars show squared error relative to the same neural model without graph messages (100%). Lower is better. This tests daily forecasting, not RL or trading. These short runs do not establish convergence.</p><div class="visual-grid" id="neural-graph-results"></div><p id="neural-graph-source" class="visual-note"></p>';
  graphScreen.after(neuralGraph);
  async function refreshNeuralGraph(){try{const response=await fetch('neural_graph.json',{cache:'no-store'});if(!response.ok){neuralGraph.hidden=true;return;}const data=await response.json();const box=el('neural-graph-results');box.replaceChildren();for(const seed of data.seeds)for(const target of ['return','volatility','downside']){const rows=data.results.filter(r=>r.seed===seed&&r.target===target&&r.period==='all');if(!rows.length)continue;const panel=document.createElement('div');panel.className='visual-panel';const heading=document.createElement('h3');heading.textContent=target+' · seed '+seed;panel.append(heading);const max=Math.max(120,...rows.map(r=>100+r.change_vs_no_graph));for(const row of rows)bar(panel,({no_graph:'Without messages',graph:'Related-stock messages',shuffled_graph:'Shuffled relationships'})[row.arm],100+row.change_vs_no_graph,max);box.append(panel);}el('neural-graph-source').textContent='Run '+data.run_id+' · '+data.epochs+' epochs per arm/fold · shared initialization and batch order within each seed. Correlation links, not audited competitor data. Complete stock histories only; reused adjusted-price sample. No news, macro or account inputs. Both seeds retained; no model selected from these results.';}catch(error){el('neural-graph-results').textContent='Neural graph comparison unavailable.';}}
  refreshNeuralGraph();
  const innerGraph=document.createElement('section');innerGraph.id='neural-inner';
  innerGraph.innerHTML='<h2>Does more training help, or just fit the past?</h2><p>Completed supervised forecast diagnostic. Green: training loss. Orange: later validation loss, checked every four epochs. Both use the same training-fitted numerical scale; lower is better. Validation dates and their outcomes finish before the named outer year. This is not an investing reward curve.</p><label>Outer year <select id="inner-year"><option>2022</option><option>2023</option><option>2024</option><option>2025</option></select></label> <label>Seed <select id="inner-seed"><option>42</option><option>43</option></select></label> <label>Model <select id="inner-arm"><option value="no_graph">Without messages</option><option value="graph">Related-stock messages</option><option value="shuffled_graph">Shuffled relationships</option></select></label><div id="inner-curve" class="visual-panel" style="margin-top:12px"></div><p id="inner-status" class="visual-note"></p>';
  neuralGraph.after(innerGraph);let innerData=null;
  function renderInner(){if(!innerData)return;const rows=innerData.history.filter(r=>String(r.year)===el('inner-year').value&&String(r.seed)===el('inner-seed').value&&r.arm===el('inner-arm').value);const box=el('inner-curve');box.replaceChildren();if(!rows.length){box.textContent='This comparison is queued; no curve yet.';return;}const ymax=Math.max(1,...rows.flatMap(r=>[r.train_loss,r.validation_loss||0]));const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 210');svg.setAttribute('role','img');svg.setAttribute('aria-label','Training and chronological validation loss from epoch 0 to 32; vertical scale 0 to '+ymax.toFixed(2));svg.style.maxWidth='900px';for(const [key,color] of [['train_loss','#7ad5c1'],['validation_loss','#f2b36f']]){const values=rows.filter(r=>Number.isFinite(r[key]));if(!values.length)continue;const line=document.createElementNS(ns,'polyline');line.setAttribute('points',values.map(r=>(50+520*r.epoch/32)+','+(170-140*r[key]/ymax)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke',color);line.setAttribute('stroke-width','2');svg.append(line);}const axis=document.createElementNS(ns,'path');axis.setAttribute('d','M50 20V170H570');axis.setAttribute('stroke','#738192');axis.setAttribute('fill','none');svg.append(axis);for(const [x,y,text] of [[4,30,ymax.toFixed(2)],[25,172,'0'],[50,192,'0 epochs'],[500,192,'32 epochs']]){const label=document.createElementNS(ns,'text');label.setAttribute('x',x);label.setAttribute('y',y);label.setAttribute('fill','#a8b6c5');label.setAttribute('font-size','13');label.textContent=text;svg.append(label);}box.append(svg);const latest=rows[rows.length-1],note=document.createElement('p');note.className='visual-note';note.textContent='Epoch '+latest.epoch+'/32 · '+latest.optimizer_updates+' optimizer updates · largest raw gradient '+latest.gradient_max.toFixed(2)+' (clipped at 1). Training loss averages batches during the epoch. A falling training curve alone does not show generalization.';box.append(note);}
  for(const id of ['inner-year','inner-seed','inner-arm'])el(id).addEventListener('change',renderInner);
  async function refreshInner(){try{const response=await fetch('neural_inner.json',{cache:'no-store'});if(!response.ok){innerGraph.hidden=true;return;}innerGraph.hidden=false;innerData=await response.json();renderInner();const age=(Date.now()-Date.parse(innerData.source_updated_at))/1000;el('inner-status').textContent=innerData.status+' · run '+innerData.run_id+' · updated '+innerData.source_updated_at+(innerData.status==='running'&&age>120?' · telemetry is stale; process may be stopped or between updates':'')+(innerData.error?' · '+innerData.error:'')+'. Three graph settings, two seeds, four chronological validation blocks; 32 fixed epochs, no adaptive stopping. Reused data; no outer-test performance claim.';}catch(error){el('inner-status').textContent='Training snapshot unavailable.';}}
  refreshInner();setInterval(refreshInner,10000);
  const budgetNote=document.createElement('p');budgetNote.className='visual-note';innerGraph.append(budgetNote);
  async function refreshBudget(){try{const response=await fetch('neural_budget.json',{cache:'no-store'});if(!response.ok)return;const data=await response.json();if(!innerData||data.run_id!==innerData.run_id){budgetNote.textContent='';return;}budgetNote.textContent='Completed budget check, epoch 8 → 32: training loss fell in '+data.training_improved+'/'+data.total+' comparisons, while validation loss worsened in '+data.validation_worsened+'/'+data.total+'. Median changes: training '+data.median_training_change.toFixed(1)+'%, validation '+data.median_validation_change.toFixed(1)+'%. This is descriptive across dependent folds and seeds, not a significance test or selected winning checkpoint.';}catch(error){budgetNote.textContent='Budget summary unavailable.';}}
  refreshBudget();setInterval(refreshBudget,30000);
  const riskAudit=document.createElement('details');riskAudit.id='risk-forecast-audit';riskAudit.innerHTML='<summary>Do risk forecasts beat recent-risk persistence?</summary><div id="risk-audit-results" class="visual-grid"></div><p class="visual-note">Diagnostic follow-up on the same adjusted-price sample. Ranges resample 20-session date blocks, retaining all stocks together. They do not account for model selection or prove trading value. Uncalibrated persistence can be a weak baseline; calibration remains to test.</p>';
  compoundScreen.append(riskAudit);
  const calibratedAudit=document.createElement('p');calibratedAudit.className='visual-note';riskAudit.prepend(calibratedAudit);
  fetch('risk_calibration.json',{cache:'no-store'}).then(response=>response.ok?response.json():null).then(data=>{if(!data)return;const rows=data.results.filter(r=>r.model==='ridge_base'&&r.baseline==='calibrated_5_20_60');calibratedAudit.textContent='Stronger baseline: fit a linear calibration of recent 5/20/60-session risk using training data only. '+rows.map(r=>r.target+': '+r.mse_change_percent.toFixed(2)+'% squared error versus calibrated risk; 20-session-block range '+r.interval20.map(v=>v.toFixed(2)+'%').join(' to ')).join('. ')+'. Same forecast dates and target values verified exactly. The smaller advantage is more informative than beating uncalibrated persistence; still no trading result.';}).catch(()=>{});
  fetch('compound_audit.json',{cache:'no-store'}).then(response=>response.ok?response.json():null).then(data=>{if(!data){riskAudit.hidden=true;return;}for(const target of ['volatility','downside']){const panel=document.createElement('div');panel.className='visual-panel';const title=document.createElement('h3');title.textContent=target==='volatility'?'Volatility forecast':'Downside forecast';panel.append(title);for(const row of data.results.filter(r=>r.target===target&&r.arm==='ridge_base')){const p=document.createElement('p');p.textContent='Versus prior '+row.window+' sessions: '+row.mse_change_percent.toFixed(1)+'% squared error; 95% resampling range '+row.intervals['20'].map(x=>x.toFixed(1)+'%').join(' to ')+'. '+row.stocks_improved+'/'+row.stocks+' stocks improved.';panel.append(p);}el('risk-audit-results').append(panel);}}).catch(()=>{riskAudit.hidden=true;});
  interestChecks.innerHTML='<h2>Completed accounting checks</h2><p>Cash interest now reaches the environment and policy. These checks verify money flows and software operation; they do not show an investing edge.</p><div id="interest-check-panels" class="visual-grid"></div><p id="interest-check-source" class="visual-note"></p>';
  view.prepend(interestChecks);
  async function refreshInterestChecks(){try{
    const response=await fetch('interest_checks.json',{cache:'no-store'});if(!response.ok){interestChecks.hidden=true;return;}
    const data=await response.json();interestChecks.hidden=false;const box=el('interest-check-panels');box.replaceChildren();
    const a=data.accounting,l=data.learner;
    const entries=[
      ['Money flow verified',a.days+' simulated calendar days','Earned → held as a receivable → credited to cash. Each of two example accounts received $'+Number(a.credited_per_account).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})+'. Another $'+Number(a.unpaid_total).toFixed(2)+' remained unpaid across both accounts. Tax reserves and replay reconcile. Fixed artificial rates; no trading performance result.'],
      ['Learner integration passed',l.steps.toLocaleString()+' steps · '+l.episodes+' complete episode',l.optimizer_steps+' optimizer updates with finite parameters and gradients. '+(l.dividend_fixture?'Combined dividend and interest inputs; completed episodes include '+l.episode_summaries.reduce((n,e)=>n+e.dividend_cash_postings,0)+' dividend cash postings. ':'The policy receives interest, income and tax-reserve features. ')+(l.split_fixture?'Also exercised '+l.episode_summaries.reduce((n,e)=>n+(e.split_postings||0),0)+' plain share splits. ':'')+'This short run checks that the components work together; it is not enough to assess learning.'],
      [data.limitation.title||'Reinvestment interest limitation','Earlier attempt stopped at step '+data.limitation.stopped_at,data.limitation.reason]
    ];
    if(data.horizon)entries.unshift(['Long holding calendar passed',data.horizon.steps.toLocaleString()+' five-minute decisions · 14 months','Scripted buys, Hold and a sale after one year. Five dividend captures, '+(data.horizon.splits||0)+' plain splits, monthly interest and per-step after-tax rewards reconcile. A December dividend becomes qualified in January while retaining its original tax year. '+(data.horizon.independent_identity?'Independent gross cash/position identity and journal replay also pass. ':'')+'This verifies accounting, not learning. Run '+data.horizon.run+'.']);
    for(const [title,metric,note] of entries){const panel=document.createElement('div');panel.className='visual-panel';const h=document.createElement('h3');h.textContent=title;const value=document.createElement('strong');value.textContent=metric;const p=document.createElement('p');p.className='visual-note';p.textContent=note;panel.append(h,value,p);box.append(panel);}
    el('interest-check-source').textContent='Accounting '+a.run+' · integration '+l.run+' · retained failure '+data.limitation.run+' · updated '+data.updated_at+'. Earlier learning comparisons remain below.';
  }catch(error){el('interest-check-panels').textContent='Accounting snapshot unavailable; no verification status inferred.';}}
  refreshInterestChecks();setInterval(refreshInterestChecks,30000);
})();
